name: ✨ 功能需求
description: 为项目提出一个新的想法或建议
labels: [ enhancement ]
body:
  - type: markdown
    attributes:
      value: |
        [GitHub Issues](https://github.com/tkgs0/nonebot-plugin-antiinsult/issues) 专门用于错误报告和功能需求，这意味着我们不接受使用问题。如果您打开的问题不符合要求，它将会被无条件关闭。

        有关使用问题，请通过以下途径：

        - 阅读文档以解决
        - 在社区内寻求他人解答
        - 在 [GitHub Discussions](https://github.com/tkgs0/nonebot-plugin-antiinsult/discussions) 上提问
        - 在网络中搜索是否有人遇到过类似的问题

        如果您不知道如何有效、精准地提出一个问题，我们建议您先阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。

        最后，请记得遵守我们的社区准则，友好交流。

  - type: markdown
    attributes:
      value: "## 注意事项"
  - type: markdown
    attributes:
      value: |
        在提 issue 前请确保你仔细阅读过文档，搜索过现有的 issue ，并确保你使用的是最新的 nonebot-plugin-antiinsult ，避免发生 “提出的需求是已经实现了的” 这种令人哭笑不得的情况。

  - type: checkboxes
    attributes:
      label: 报告清单
      description: 请确认您已遵守所有必选项。
      options:
        - label: 我已仔细阅读并了解上述注意事项。
          required: true
        - label: 我已使用最新版本测试过，确认功能并未实现。
          required: true
        - label: 我确定在 [GitHub Issues](https://github.com/tkgs0/nonebot-plugin-antiinsult/issues) 中没有相同或相似的需求。
          required: true
        - label: 我有足够的时间和能力，愿意为此提交 [PR](https://github.com/tkgs0/nonebot-plugin-antiinsult/pulls) 来实现功能。
          required: false

  - type: textarea
    attributes:
      label: 您希望能解决什么样的问题？
      description: 请简要地说明是什么问题导致您想要一个新功能。也许我们可以提出一种现有的解决办法。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 您想要的解决方案
      description: 请说明您希望使用什么样的方法解决上述问题。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 您考虑过的替代方案
      description: 除了上述方法以外，您还考虑过哪些其他的实现方式？
    validations:
      required: false

  - type: textarea
    attributes:
      label: 实现的功能是什么样的？
      description: |
        提供功能在实现后如何使用的代码示例。
        请注意，您可以使用 Markdown 来设置代码块的格式。
        尽可能多地提供细节。您希望它如何使用的示例代码会有所帮助。
    validations:
      required: false

  - type: textarea
    attributes:
      label: 额外补充
      description: 在此处添加相关的任何其他上下文或截图，或者您觉得有帮助的信息。
    validations:
      required: false

