name: 功能需求
description: 希望添加一个功能
labels: [ enhancement ]
body:
  - type: markdown
    attributes:
      value: |
        提新功能需求之前，请确保你使用的是最新的 nonebot-plugin-antiinsult ，并仔细阅读文档，避免发生“提出的需求是已经实现了的”这种令人哭笑不得的情况。

  - type: textarea
    id: feature
    attributes:
      label: 功能需求
      placeholder: 希望添加的功能是什么？
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 理由
      placeholder: 为什么要添加这个功能？
    validations:
      required: true
